=== TATJAVA-Uladzislau-Seuruk/TATJAVA01_2017_Task05_Uladzislau_Seuruk/src/main/resources/menu_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.tat.epam.com/menu"
  xmlns:tns="http://www.tat.epam.com/menu"
  elementFormDefault="qualified">

  <element name="menu">
    <complexType>
      <all>
        <element name="coldAppetizers" type="tns:Section" minOccurs="0"/>
        <element name="hotAppetizers" type="tns:Section" minOccurs="0"/>
        <element name="breakfasts" type="tns:Section" minOccurs="0"/>
        <element name="salads" type="tns:Section" minOccurs="0"/>
        <element name="soups" type="tns:Section" minOccurs="0"/>
        <element name="fishDishes" type="tns:Section" minOccurs="0"/>
        <element name="meatDishes" type="tns:Section" minOccurs="0"/>
        <element name="sideDishes" type="tns:Section" minOccurs="0"/>
        <element name="grillDishes" type="tns:Section" minOccurs="0"/>
        <element name="chefSpecial" type="tns:Section" minOccurs="0"/>
        <element name="annex" type="tns:Section" minOccurs="0"/>
        <element name="desserts" type="tns:Section" minOccurs="0"/>
      </all>
    </complexType>
  </element>

  <complexType name="Section">
    <sequence>
      <element name="item" type="tns:Item" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="Item">
    <sequence>
      <element name="photoUri" type="anyURI" minOccurs="0"/>
      <element name="name" type="string"/>
      <element name="description" type="string" minOccurs="0"/>
      <element name="portion" type="string"/>
      <element name="price" type="string" minOccurs="0"/>
    </sequence>
    <attribute name="id" type="ID" use="required"/>
  </complexType>

</schema>

=== TATJAVA-Uladzislau-Seuruk/TATJAVA01_2017_Task05_Uladzislau_Seuruk/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<menu xmlns="http://www.tat.epam.com/menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.tat.epam.com/menu src/main/resources/menu_schema.xsd">
  <coldAppetizers>
    <item id="ca-1">
      <name>Ассорти рыбное</name>
      <description>Слабофасоленая форель, семга</description>
      <portion>100/20/15</portion>
    </item>
    <item id="ca-2">
      <name>Тарталетки с красной икрой</name>
      <description>Тарталетки с красной икрой</description>
      <portion>60/50</portion>
    </item>
    <item id="ca-3">
      <name>Закуска по-русски</name>
      <description>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</description>
      <portion>70/50/2/10</portion>
    </item>
    <item id="ca-4">
      <name>Куриный рулет</name>
      <description>Куриный рулет собственного производства</description>
      <portion>100/5</portion>
    </item>
    <item id="ca-5">
      <name>Баструма</name>
      <description>Вяленая вырезка из говяжьего мяса</description>
      <portion>50/5</portion>
    </item>
    <item id="ca-6">
      <name>Ассорти мясное</name>
      <description>Нарезка из буженины, баструмы, куриного рулета собственного производства и колбасы</description>
      <portion>100/30</portion>
    </item>
    <item id="ca-7">
      <name>Язык отварной</name>
      <description>Нарезка нежного говяжьего языка, подается с хреном</description>
      <portion>80/20/1</portion>
    </item>
    <item id="ca-8">
      <name>Ассорти баклажаны</name>
      <description>Жаренные баклажаны с помидорами
        1. с помидорами
        2. с чесноком
        3. с орехами</description>
      <portion>100/5</portion>
    </item>
    <item id="ca-9">
      <name>Соленья по-домашнему</name>
      <description>Маринованные овощи</description>
      <portion>150/10</portion>
    </item>
    <item id="ca-10">
      <name>Бабушкины угощения</name>
      <description>Ассорти из маринованных грибов</description>
      <portion>120/20/10</portion>
    </item>
    <item id="ca-11">
      <name>Сырная тарелка</name>
      <description>Сыры Чечел, дор блю, российский, мраморный</description>
      <portion>100/5</portion>
    </item>
    <item id="ca-12">
      <name>Брынза</name>
      <description>Рассольный сыр, изготавливаемый из овечьего молока</description>
      <portion>75/5</portion>
    </item>
    <item id="ca-13">
      <name>Зелень</name>
      <description>Кинза, лук, петрушка, укроп, базилик</description>
      <portion>30</portion>
    </item>
    <item id="ca-14">
      <name>Ассорти овощное</name>
      <description>Свежие помидоры, болгарский перец, огурцы редис и зелень</description>
      <portion>150/10</portion>
    </item>
    <item id="ca-15">
      <name>Овощной букет</name>
      <description>Корейская морковь, капуста, фунчоза</description>
      <portion>150/10</portion>
    </item>
    <item id="ca-16">
      <name>Овощи по-армянски</name>
      <description>Мелко нарезанные свежие помидоры, огурцы, болгарский перец, укроп, базилик, кинза, лист салата, зелень</description>
      <portion>150/40</portion>
    </item>
    <item id="ca-17">
      <name>Сеньор помидор</name>
      <description>Помидор, фаршированный сырным сырным муссом</description>
      <portion>150/1</portion>
    </item>
    <item id="ca-18">
      <name>Фестиваль салатов</name>
      <portion>400/10</portion>
    </item>
    <item id="ca-19">
      <name>Оливки, маслины</name>
      <portion>50</portion>
    </item>
    <item id="ca-20">
      <name>Лимон</name>
      <portion>60</portion>
    </item>
    <item id="ca-21">
      <name>Мацони</name>
      <portion>300</portion>
    </item>
  </coldAppetizers>

  <hotAppetizers>
    <item id="ha-1">
      <name>Лобио с шампиньонами</name>
      <description>Фасоль с шампиньонами и грецким орехом</description>
      <portion>150/5</portion>
      <price>105</price>
    </item>
    <item id="ha-2">
      <name>Жульен</name>
      <description>1. с курицей
        2. с грибами </description>
      <portion>120/1</portion>
      <price>1. 145
        2. 155</price>
    </item>
    <item id="ha-3">
      <name>Ахматар мясной</name>
      <description>Колбаса, ветчина, буженина, сыр, запеченные на мангале в лаваше</description>
      <portion>1 шт.</portion>
      <price>165</price>
    </item>
    <item id="ha-4">
      <name>Ахматар с овощами</name>
      <description>Сыр, помидоры, зелень, запеченные на мангале в лаваше</description>
      <portion>1 шт.</portion>
      <price>150</price>
    </item>
    <item id="ha-5">
      <name>Сюрприз</name>
      <portion>1 шт.</portion>
      <price>260</price>
    </item>
    <item id="ha-6">
      <name>Креветки</name>
      <description>1. отварные
        2. жаренные</description>
      <portion>120/30</portion>
      <price>1. 135
        2.155</price>
    </item>
    <item id="ha-7">
      <name>Мидии по-туррецки</name>
      <description>Мидии, фаршированные сыром и грецким орехом</description>
      <portion>150/30</portion>
      <price>190</price>
    </item>
    <item id="ha-8">
      <name>Эскарго</name>
      <description>Виноградные улитки, фаршированные по бургундски</description>
      <portion>12 шт.</portion>
      <price>230</price>
    </item>
  </hotAppetizers>

  <breakfasts>
    <item id="br-1">
      <name>Глазунья</name>
      <description>2 яйца (на выбор: ветчина, сыр, помидоры)</description>
      <portion>150</portion>
    </item>
    <item id="br-2">
      <name>Омлет</name>
      <portion>100</portion>
    </item>
    <item id="br-3">
      <name>Блинчики с мясом</name>
      <description>Жаренные блинчики с мясом</description>
      <portion>150</portion>
    </item>
  </breakfasts>
</menu>
